const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Plugins.Date,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Browser.Acts.SetWindowSize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetMonth,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.AnimationFrame
	];
};
self.C3_JsPropNameTable = [
	{Box_White: 0},
	{Box_White2: 0},
	{Box_White3: 0},
	{Box_White4: 0},
	{Box_White5: 0},
	{Box_White6: 0},
	{NameBOX_2: 0},
	{NameBOX_4: 0},
	{NameBOX_5: 0},
	{NameBOX_6: 0},
	{NameBOX_7: 0},
	{NameBOX_8: 0},
	{Text_Option1: 0},
	{Text_Option2: 0},
	{Text_Option3: 0},
	{Text_Option4: 0},
	{Text_Option5: 0},
	{Text_Option6: 0},
	{Sprite6: 0},
	{Tween: 0},
	{Input_img: 0},
	{TiledBackground2: 0},
	{BG: 0},
	{DermaQuest_Logo: 0},
	{Shape_: 0},
	{Text_Timer: 0},
	{Audio: 0},
	{Browser: 0},
	{ArrayQuestionNumber: 0},
	{TextDebug_QuestionNumber: 0},
	{play: 0},
	{Touch: 0},
	{TextDebug_QuestionArray: 0},
	{TextDebug_ArrayWidth: 0},
	{smile: 0},
	{TextBox_ThankYou: 0},
	{Button_Explore: 0},
	{Text_Home_ThankYou: 0},
	{Text_Home_ThankYou2: 0},
	{Text_Home_ThankYou3: 0},
	{home_Button: 0},
	{Text_HowTo_1: 0},
	{Text_HowTo_Start: 0},
	{Shape_2: 0},
	{Button_Start: 0},
	{Object: 0},
	{Situation_Sun: 0},
	{Bar_: 0},
	{Bar_2: 0},
	{Clock: 0},
	{Female_Character: 0},
	{Healthy_skin: 0},
	{NameBOX_: 0},
	{NameBOX_3: 0},
	{Text: 0},
	{Sprite_SunScreen1: 0},
	{Sprite_SunScreen2: 0},
	{Situation_Dust: 0},
	{Situation_Stress: 0},
	{Fade: 0},
	{correct: 0},
	{incorrect: 0},
	{Sprite_WetWipes: 0},
	{Sprite_WetWipes2: 0},
	{Situation_Serum: 0},
	{Situation_Lips: 0},
	{Situation_Dehydration: 0},
	{Sprite_Serum1: 0},
	{Sprite_Serum2: 0},
	{Sprite_Lipbalm: 0},
	{Sprite_Water: 0},
	{Sprite_Meditation: 0},
	{Diaologue: 0},
	{Sprite3: 0},
	{header: 0},
	{ok_btn: 0},
	{Reward: 0},
	{ScreenshotItAndShowAtThePaymentCounterForDiscount: 0},
	{Shape: 0},
	{Text_Score_1: 0},
	{Sprite4: 0},
	{Text_Score_2: 0},
	{Mute: 0},
	{Text_Mute: 0},
	{Text_BetterLuck: 0},
	{Text_Score_Percent: 0},
	{opps: 0},
	{Text_SkinHealth: 0},
	{Text_Date: 0},
	{Date: 0},
	{Text_Reward: 0},
	{Button_Back: 0},
	{Name: 0},
	{Email: 0},
	{Submit: 0},
	{Sprite: 0},
	{Email_Id: 0},
	{Phone: 0},
	{DermaQuest_Logo2: 0},
	{AJAX: 0},
	{Text_Response: 0},
	{SaveName: 0},
	{SaveEmailBox: 0},
	{SavePhone: 0},
	{SaveEmailBox2: 0},
	{SaveName2: 0},
	{SavePhone2: 0},
	{Button2: 0},
	{JSON: 0},
	{Txt_UserId: 0},
	{Text3: 0},
	{Text4: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sprite7: 0},
	{StarID: 0},
	{Star: 0},
	{Full: 0},
	{Sprite8: 0},
	{Text2: 0},
	{Text5: 0},
	{Submit_2: 0},
	{TextBox: 0},
	{Submit_user: 0},
	{TextInput: 0},
	{DermaQuest_Logo3: 0},
	{Sine: 0},
	{DermaQuest_Splash: 0},
	{Bar_3: 0},
	{Button: 0},
	{Text6: 0},
	{Rate: 0},
	{Button3: 0},
	{RateUs: 0},
	{ThankYou: 0},
	{TFamily_Home: 0},
	{Family_Text_Home: 0},
	{Discount: 0},
	{canPlay: 0},
	{maxTimer: 0},
	{play_time: 0},
	{currentQuestion: 0},
	{PlayerId: 0},
	{Mongo: 0},
	{OptionNumberChosen: 0},
	{correctAnswer: 0},
	{currentHealth: 0},
	{questionsRemaining: 0},
	{UserName: 0},
	{MongoId: 0},
	{FinalScore: 0},
	{SelectedRating: 0},
	{PhoneNumber: 0},
	{timerCount: 0},
	{QuestionNumber: 0},
	{optionNo: 0},
	{Correct: 0},
	{isTimeUp: 0},
	{currentQues: 0},
	{ansCorrect: 0},
	{Increase: 0}
];

self.InstanceType = {
	Box_White: class extends self.ISpriteInstance {},
	Box_White2: class extends self.ISpriteInstance {},
	Box_White3: class extends self.ISpriteInstance {},
	Box_White4: class extends self.ISpriteInstance {},
	Box_White5: class extends self.ISpriteInstance {},
	Box_White6: class extends self.ISpriteInstance {},
	NameBOX_2: class extends self.ISpriteInstance {},
	NameBOX_4: class extends self.ISpriteInstance {},
	NameBOX_5: class extends self.ISpriteInstance {},
	NameBOX_6: class extends self.ISpriteInstance {},
	NameBOX_7: class extends self.ISpriteInstance {},
	NameBOX_8: class extends self.ISpriteInstance {},
	Text_Option1: class extends self.ITextInstance {},
	Text_Option2: class extends self.ITextInstance {},
	Text_Option3: class extends self.ITextInstance {},
	Text_Option4: class extends self.ITextInstance {},
	Text_Option5: class extends self.ITextInstance {},
	Text_Option6: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Input_img: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	BG: class extends self.ISpriteInstance {},
	DermaQuest_Logo: class extends self.ISpriteInstance {},
	Shape_: class extends self.ISpriteInstance {},
	Text_Timer: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ArrayQuestionNumber: class extends self.IArrayInstance {},
	TextDebug_QuestionNumber: class extends self.ITextInstance {},
	play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TextDebug_QuestionArray: class extends self.ITextInstance {},
	TextDebug_ArrayWidth: class extends self.ITextInstance {},
	smile: class extends self.ISpriteInstance {},
	TextBox_ThankYou: class extends self.ISpriteInstance {},
	Button_Explore: class extends self.ISpriteInstance {},
	Text_Home_ThankYou: class extends self.ITextInstance {},
	Text_Home_ThankYou2: class extends self.ITextInstance {},
	Text_Home_ThankYou3: class extends self.ITextInstance {},
	home_Button: class extends self.ISpriteInstance {},
	Text_HowTo_1: class extends self.ITextInstance {},
	Text_HowTo_Start: class extends self.ITextInstance {},
	Shape_2: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Object: class extends self.ISpriteInstance {},
	Situation_Sun: class extends self.ISpriteInstance {},
	Bar_: class extends self.ISpriteInstance {},
	Bar_2: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	Female_Character: class extends self.ISpriteInstance {},
	Healthy_skin: class extends self.ISpriteInstance {},
	NameBOX_: class extends self.ISpriteInstance {},
	NameBOX_3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite_SunScreen1: class extends self.ISpriteInstance {},
	Sprite_SunScreen2: class extends self.ISpriteInstance {},
	Situation_Dust: class extends self.ISpriteInstance {},
	Situation_Stress: class extends self.ISpriteInstance {},
	correct: class extends self.ISpriteInstance {},
	incorrect: class extends self.ISpriteInstance {},
	Sprite_WetWipes: class extends self.ISpriteInstance {},
	Sprite_WetWipes2: class extends self.ISpriteInstance {},
	Situation_Serum: class extends self.ISpriteInstance {},
	Situation_Lips: class extends self.ISpriteInstance {},
	Situation_Dehydration: class extends self.ISpriteInstance {},
	Sprite_Serum1: class extends self.ISpriteInstance {},
	Sprite_Serum2: class extends self.ISpriteInstance {},
	Sprite_Lipbalm: class extends self.ISpriteInstance {},
	Sprite_Water: class extends self.ISpriteInstance {},
	Sprite_Meditation: class extends self.ISpriteInstance {},
	Diaologue: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	header: class extends self.ISpriteInstance {},
	ok_btn: class extends self.ISpriteInstance {},
	Reward: class extends self.ISpriteInstance {},
	ScreenshotItAndShowAtThePaymentCounterForDiscount: class extends self.ISpriteInstance {},
	Shape: class extends self.ISpriteInstance {},
	Text_Score_1: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text_Score_2: class extends self.ITextInstance {},
	Mute: class extends self.ISpriteInstance {},
	Text_Mute: class extends self.ITextInstance {},
	Text_BetterLuck: class extends self.ITextInstance {},
	Text_Score_Percent: class extends self.ITextInstance {},
	opps: class extends self.ISpriteInstance {},
	Text_SkinHealth: class extends self.ITextInstance {},
	Text_Date: class extends self.ITextInstance {},
	Date: class extends self.IInstance {},
	Text_Reward: class extends self.ITextInstance {},
	Button_Back: class extends self.ISpriteInstance {},
	Name: class extends self.ITextInputInstance {},
	Email: class extends self.ITextInstance {},
	Submit: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Email_Id: class extends self.ITextInputInstance {},
	Phone: class extends self.ITextInputInstance {},
	DermaQuest_Logo2: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Text_Response: class extends self.ITextInstance {},
	SaveName: class extends self.ITextInstance {},
	SaveEmailBox: class extends self.ITextInstance {},
	SavePhone: class extends self.ITextInstance {},
	SaveEmailBox2: class extends self.ITextInstance {},
	SaveName2: class extends self.ITextInstance {},
	SavePhone2: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	JSON: class extends self.IJSONInstance {},
	Txt_UserId: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Full: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Submit_2: class extends self.ISpriteInstance {},
	TextBox: class extends self.ISpriteInstance {},
	Submit_user: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	DermaQuest_Logo3: class extends self.ISpriteInstance {},
	DermaQuest_Splash: class extends self.ISpriteInstance {},
	Bar_3: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Text6: class extends self.ITextInstance {},
	Rate: class extends self.ISpriteInstance {},
	Button3: class extends self.IButtonInstance {},
	RateUs: class extends self.ITextInstance {},
	ThankYou: class extends self.ITextInstance {},
	TFamily_Home: class extends self.ISpriteInstance {},
	Family_Text_Home: class extends self.ITextInstance {}
}